### ISSUE TITLE
Corrigir Problema de layout na Lista de usuários cadastrados-ADM

### ISSUE THREAD

**Issue by PvMeira** [PvMeira/Controle-Leitura#89]
Em baixas resoluções, a coluna de ações buga e mostra cada ação uma embaixo da outra
Retirar  o texto do botão deixando apenas o ícone como no exemplo abaixo:  
Antigo -(ícone) Deletar
Novo   -(ícone)

**Comment by pedrov123** [comment]
ez rekt
